### ISSUE TITLE
[enhancement] better integration with themes

### ISSUE THREAD

**Issue by danieltomasz** [rien7/obsidian-colorful-tag#15]
This plugin is great! It achieves what I was trying to achieve what I was trying to manually define via css.

Would be great to have a way to define of color and other settings of the tag and retain the ways the themes redefine the tags

Here is an for example colorful tags vs minimal

<img width="241" alt="image" src="https://user-images.githubusercontent.com/7980381/197895903-653cc7db-013e-4aa4-98a0-cebcf9fd20a2.png">

Especially  would be great if the size and the shape of the pill can stay the  same  between tag defined via plugin and via theme?
It could be non default global toggle for the users that allows for it

**Comment by danieltomasz** [comment]
Also those tags are sometimes too big  
<img width="626" alt="image" src="https://user-images.githubusercontent.com/7980381/197904859-1a68d661-d6ae-4620-b587-682d14ffb6d5.png">

**Comment by rien7** [comment]
try 1.1.2

**Comment by danieltomasz** [comment]
Thanks! This solved my issue!

I liked the style of the tags you shipped earlier maybe some other users like it too, if this is not a burden for you might be  good idea to leave it as a toggle for user to use your theme setting or the plugin defined theme?

Thanks again for this wonderful plugin!

**Comment by rien7** [comment]
If you turn on the global settings and leave it blank, the theme settings are used, otherwise the theme settings are overridden by plugin setting.
