### ISSUE TITLE
[enhancement] after setting global setting user can overwrite the setting on the tag basis

### ISSUE THREAD

**Issue by danieltomasz** [rien7/obsidian-colorful-tag#17]
Just an idea:
Currently:
- I am setting the color of text to black globally
- after settings this globally the option to set text color per tag basis is removed

What I would expect
- the setting isn't removed
- the text is black until the user set in the specific tag settings color to the different  one
- so the specify tag settings (local) can override the global ones, the local one might be just local later in the css file

**Comment by rien7** [comment]
But the setting of each tag would be very long, and I will think of a more reasonable way to solve it.

**Comment by danieltomasz** [comment]
What I meant the same mechanism you use for default settings in the "Global Settings";

- After user set a value in "Global settings" the value us the default one for every user defined tag, for example the black color of the text
- If for some reason user want to change it (for example user has one tag with dark color background that is hard to see black text and want to change the color of the text to white, the user can input the value for white in the "text color" in the specified tag, text color in  the other tags is still black)

From the technical point of view, I am not sure how this might works, but my initial idea is:
- if the field for tag is empty - populate css value from global settings
- if the  specific field in the specific tag is not empty - populate css value from the tag local settings
I think this should be computationally heavy :P 

And again, thank you for your work!

**Comment by danieltomasz** [comment]
Or the setting of each tag has only added field if the field is set by user, otherwise tag css is governed by global setting;
Sorry If I am not clear what I want to convey, 

Currently the ability to set the property of specific tag dissappear when I set the same property globally via Global settings,
(the field in tag settings is gone)
What I want
- Global setting work like now but the user still have the ability to set this property per tag basis, if user didnt set any property at the local tag, the property from "global settings' are used

**Comment by rien7** [comment]
try 1.1.4

**Comment by danieltomasz** [comment]
thanks, this is really useful! I am closing this as this is solving my issue :)
