### ISSUE TITLE
Is it possible to work with editing mode, especially live preview mode?

### ISSUE THREAD

**Issue by XMB-7** [rien7/obsidian-colorful-tag#22]
Currently, it seems to only work with the reading mode, not sure if it is a personal problem.

**Comment by rien7** [comment]
it's can work with editing mode and live preview mode. You can check your theme settings and css snippets to see if the plugin's settings are overridden.

**Comment by XMB-7** [comment]
With the default theme and all css snippets switched off, it still only works with reading mode. 
I even switched off all plugins relevant to tags. 
Not sure it's a bug or conflicts with something, waiting to see if other user would experience the same issue.  
![image](https://user-images.githubusercontent.com/65625632/199310973-49e59a7b-d7ce-48f6-8cfe-aa703722ba0d.png)
![image](https://user-images.githubusercontent.com/65625632/199311154-6dc91e9d-5b67-4036-b3f0-1bc132a15baa.png)

**Comment by rien7** [comment]
see #21, obsidian does not provide proper class name when the tag has CJK characters.

**Comment by XMB-7** [comment]
Thanks a lot, looking forward to the bug fix soon.
Maybe you could leave #21 open to temporarily remind CJK users.
