### ISSUE TITLE
Frustrating (Where's the user guide?)

### ISSUE THREAD

**Issue by NoobAndProud-01** [rien7/obsidian-colorful-tag#28]
Hi, I was exited to have this plug-in but it's kind of useless as is.
Issues:
-No user guide, there a picture (https://github.com/rien7/obsidian-colorful-tag/blob/master/assets/setting.png) but that's it, how do I get the big tag? Is it possible? 

-"Background color: #fff" "Text color: #000" wtf!? Maybe a color picker for us mortals?

-Font weight, default= 900, change to 1500, font gets thinner, change to 300, font gets thinner 😤 

-~~Radius does nothing neither, it's either square or round tag~~ (Found it! you have to type "px" maybe a sliding button wold be better?)

-"Border": Tried #fff, "#000" "White" "12px" "Yes" "no" "please?" no border.

-"Tag Item": Not working. Left box> "Hi" right box> "{{DATE}}" nothing. reverse input, nothing

-Uber annoying bug: every time I try to select text from any box the whole window ghost moves like I'm moving a picture on a web site. 

-And last, I'd like to get some nested tags with the add-on but so far no luck and can't find how to online.

Useful info: Obsidian 1.3 on Windows 10, Default theme, Tag Wrangler plugin (not activated)

Thank you!

**Comment by rien7** [comment]
Sorry for the bad experience, you can read the new readme now.
