### ISSUE TITLE
Format text option

### ISSUE THREAD

**Issue by kmaustral** [rien7/obsidian-colorful-tag#4]
It would be good to be able to change the size of the font used in the tag. 

Many thanks for this useful plugin.

**Comment by rien7** [comment]
Do you want to specify the size of one label or all labels just like setting round corner?

**Comment by kmaustral** [comment]
A setting for all labels would be enough. Others might want different
format for specific tags, but that might come later.

Thank you
Kevin

_______
Merri-bek, Melbourne, Narrm, Australia
📅 Sunday, 16 October 02022
Poorneet season 🦜 myrnong daisies flower, pied currawongs call
🌖 Waning gibbous moon
🌡️ Partly cloudy. Medium (50%) chance of showers, becoming less likely
late this afternoon and evening. Light winds becoming south to
southwesterly 15 to 20 km/h in the middle of the day then becoming light in
the evening. 16℃
🌏 Current CO2 is 415.95 ppm.
🤔 "How could we be chilled by the cold breath of the sciences, when the
sciences are hot and fragile, human and controversial, full of thinking
reeds and of subjects who are themselves inhabited by things?" Bruno
Latour, We Have Never Been Modern

**Comment by rien7** [comment]
I have added this feature in 1.0.4
