### ISSUE TITLE
nested tags are not working

### ISSUE THREAD

**Issue by ealizadeh-via** [rien7/obsidian-colorful-tag#9]
Thanks for developing this nice plugin. The plugin doesn't work with nested tags like `#a/b`. 

![Screen Shot 2022-10-20 at 11 43 38 PM](https://user-images.githubusercontent.com/84460342/197106726-554bedbf-b96d-4d28-a202-0d3f3016fe2b.png)

**Comment by rien7** [comment]
I fixed it in 1.0.3
